---
- name: Инициализация swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token

- name: Сохранение токена
  ansible.builtin.set_fact:
    token_manager: "{{ token.swarm_facts.JoinTokens.Manager }}"
    token_worker: "{{ token.swarm_facts.JoinTokens.Worker }}"
    # кеширование для переиспользования
    cacheable: true
# - name: Сохранение токена manager
#   ansible.builtin.copy:
#     dest: ./tokens/token-manager
#     content: "{{ token.swarm_facts.JoinTokens.Manager }}"
#     mode: "0777"
#   delegate_to: localhost

# - name: Сохранение токена worker
#   ansible.builtin.copy:
#     dest: ./tokens/token-worker
#     content: "{{ token.swarm_facts.JoinTokens.Worker }}"
#     mode: "0777"
#   delegate_to: localhost
